import { DEFAULT_TOKENS } from "../theme/tokenMeta";
import type { OrnamentId } from "./ornaments";

export const SAMPLE_HERO = "/sample/feature.jpg";

export const TEMPLATE_IDS = [
  "slant",
  "broadcast",
  "ticker",
  "story",
  "board",
  "movers",
  "power",
  "split",
] as const;
export type TemplateId = (typeof TEMPLATE_IDS)[number];

export type TemplateDef = {
  id: TemplateId;
  name: string;
  blurb: string;
  swatches: [string, string, string];
  thumb?: string;
  hero?: string;
  ornaments: Record<"a" | "b" | "c" | "d", OrnamentId>;
  tokens: Record<string, string>;
};

export const TEMPLATES: TemplateDef[] = [
  {
    id: "slant",
    name: "Slant",
    blurb: "Gold Instagram bars",
    swatches: ["#07080c", "#e4b53c", "#ffffff"],
    ornaments: { a: "burst", b: "soccer", c: "none", d: "none" },
    tokens: {},
  },
  {
    id: "broadcast",
    name: "Broadcast",
    blurb: "TV ticker, circle crests",
    swatches: ["#0b0d12", "#c8102e", "#f4f4f4"],
    ornaments: { a: "none", b: "none", c: "none", d: "none" },
    tokens: {
      "--poster-bg": "#0b0d12",
      "--poster-accent": "#c8102e",
      "--header-bar": "#c8102e",
      "--rank-fg": "#ffffff",
      "--rank-size": "40px",
      "--rank-width": "72px",
      "--name-skew": "0",
      "--sparkle-opacity": "0",
      "--row-gap": "6px",
      "--row-height": "76px",
      "--logo-size": "64px",
      "--title-size": "76px",
      "--title-tracking": "0.04em",
      "--name-size": "26px",
      "--pts-bg": "#c8102e",
      "--pts-fg": "#ffffff",
      "--deco-opacity": "0.28",
      "--font-display": '"Bebas Neue", Impact, sans-serif',
      "--font-body": '"Oswald", "Arial Narrow", sans-serif',
      "--font-footer": '"Oswald", "Arial Narrow", sans-serif',
      "--row-edge": "7px",
      "--logo-scale": "89",
    },
  },
  {
    id: "ticker",
    name: "Ticker",
    blurb: "Box-score newsprint",
    swatches: ["#efe6d4", "#8b1a1a", "#1a1612"],
    ornaments: { a: "none", b: "none", c: "none", d: "none" },
    tokens: {
      "--poster-bg": "#efe6d4",
      "--poster-fg": "#1a1612",
      "--poster-muted": "#5c5348",
      "--poster-accent": "#8b1a1a",
      "--header-bar": "#1a1612",
      "--rank-fg": "#8b1a1a",
      "--rank-size": "22px",
      "--rank-width": "48px",
      "--name-skew": "0",
      "--sparkle-opacity": "0",
      "--row-gap": "0px",
      "--row-height": "62px",
      "--logo-size": "52px",
      "--title-size": "62px",
      "--title-tracking": "0.01em",
      "--name-size": "22px",
      "--stat-size": "18px",
      "--pts-bg": "#1a1612",
      "--pts-fg": "#efe6d4",
      "--deco-opacity": "0.2",
      "--font-display": '"Playfair Display", Georgia, serif',
      "--font-body": '"Oswald", "Arial Narrow", sans-serif',
      "--font-footer": '"Playfair Display", Georgia, serif',
    },
  },
  {
    id: "story",
    name: "Story",
    blurb: "Giant rank watermarks",
    swatches: ["#090909", "#ff3b30", "#ffffff"],
    ornaments: { a: "stars", b: "none", c: "none", d: "none" },
    tokens: {
      "--poster-bg": "#090909",
      "--poster-accent": "#ff3b30",
      "--header-bar": "#ff3b30",
      "--rank-fg": "#ff3b30",
      "--rank-size": "46px",
      "--rank-width": "78px",
      "--name-skew": "0",
      "--sparkle-opacity": "0.18",
      "--row-gap": "8px",
      "--row-height": "86px",
      "--title-size": "84px",
      "--name-size": "32px",
      "--pts-bg": "#ff3b30",
      "--pts-fg": "#ffffff",
      "--deco-opacity": "0.32",
      "--font-display": '"Anton", Impact, sans-serif',
      "--font-body": '"Oswald", "Arial Narrow", sans-serif',
      "--ghost-opacity": "0.16",
      "--ghost-size": "128px",
    },
  },
  {
    id: "board",
    name: "State",
    blurb: "Sticker title, full-bleed Top 15 bars, rating panel",
    swatches: ["#b4b4b4", "#b4caef", "#1a2748"],
    ornaments: { a: "none", b: "none", c: "none", d: "none" },
    /*
      Measured off the published 1080x1350 State Top 15 graphic:
      20px side pad · 104+54 white plate · 128 crest · name from x=306 · 418 stat panel
      (3 x 139) · 74px bars on a 75px pitch · first bar at y=206.
    */
    tokens: {
      "--poster-bg": "#b4b4b4",
      "--poster-fg": "#1a2748",
      "--poster-muted": "#2a3a5c",
      "--poster-accent": "#b4caef",
      "--title-outline": "#ffffff",
      "--header-bar": "transparent",
      "--col-head-fg": "#b4caef",
      "--title-size": "104px",
      "--title-tracking": "-0.015em",
      "--eyebrow-size": "58px",
      "--meta-size": "16px",
      "--meta-y": "-10px",
      /* Flush 74px bars, title sitting in the upper third. Two-line names keep the
         same Oswald size as one-liners and centre as a block inside the bar. */
      "--header-height": "176px",
      "--title-y": "8px",
      "--footer-height": "0px",
      "--col-head-height": "44px",
      "--col-head-size": "36px",
      "--col-head-outline": "5px",
      "--cols-y": "8px",
      "--poster-pad": "20px",
      "--row-height": "74px",
      "--row-gap": "0px",
      "--row-radius": "0px",
      "--seg-gap": "0px",
      "--plate-inset": "0px",
      "--name-size": "44px",
      "--name-line": "0.82",
      "--name-skew": "0",
      "--name-pad": "-16px",
      "--rank-fg": "#1a2748",
      "--rank-size": "40px",
      "--rank-width": "54px",
      "--trend-width": "104px",
      "--trend-gap": "8px",
      "--stat-size": "34px",
      "--stat-col-width": "139px",
      "--pts-box": "140px",
      "--logo-size": "128px",
      "--mark-pad-x": "14px",
      "--mark-pad-y": "4px",
      "--stat-tint": "26",
      "--sparkle-opacity": "0",
      "--deco-opacity": "0",
      "--board-width": "100",
      "--font-display": '"Luckiest Guy", Impact, sans-serif',
      "--font-body": '"Oswald", "Arial Narrow", sans-serif',
      "--font-footer": '"Oswald", "Arial Narrow", sans-serif',
      "--highlight-rank": "0",
      "--move-up": "#1f9d4d",
      "--move-down": "#e23b36",
      "--move-flat": "#5c6570",
      "--title-shade": "#7f8894",
      "--title-shade-depth": "0px",
      "--outline-width": "12px",
      "--eyebrow-outline": "8px",
      "--rule-width": "0px",
      "--rule-height": "8px",
      "--hot-edge": "0px",
      "--arrow-size": "34px",
      "--kicker-tracking": "0.06em",
      "--plate-bg": "#ffffff",
      /* Sampled from the graphic: every rank and movement number prints this indigo. */
      "--plate-ink": "#6d5899",
      "--bar-ink": "#ffffff",
      "--bar-ink-on-light": "#1a2748",
    },
  },
  {
    id: "movers",
    name: "Movers",
    blurb: "Biggest Movers — split plates, one rating column",
    swatches: ["#050505", "#a8d4f5", "#ffffff"],
    ornaments: { a: "none", b: "none", c: "none", d: "none" },
    /*
      Measured off the published 1080x1350 Biggest Movers graphic: same skin as State with
      the plate split in two by --seg-gap, one 275px rating column, and ten 86px bars.
    */
    tokens: {
      "--poster-bg": "#050505",
      "--poster-fg": "#ffffff",
      "--poster-muted": "#b8c6d6",
      "--poster-accent": "#a8d4f5",
      "--title-outline": "#ffffff",
      "--header-bar": "transparent",
      "--col-head-fg": "#ffffff",
      "--title-size": "104px",
      "--title-tracking": "-0.01em",
      "--eyebrow-size": "104px",
      "--meta-size": "16px",
      "--meta-y": "-14px",
      "--header-height": "270px",
      "--footer-height": "0px",
      "--col-head-height": "46px",
      "--col-head-size": "38px",
      "--col-head-outline": "5px",
      "--poster-pad": "12px",
      "--row-height": "86px",
      "--row-gap": "6px",
      "--row-radius": "0px",
      "--seg-gap": "12px",
      "--plate-inset": "0px",
      "--name-size": "46px",
      "--name-line": "0.82",
      "--name-skew": "0",
      "--name-pad": "4px",
      "--rank-fg": "#1a2748",
      "--rank-size": "38px",
      "--rank-width": "92px",
      "--trend-width": "104px",
      "--trend-gap": "4px",
      "--move-size": "42px",
      "--stat-size": "40px",
      "--stat-col-width": "139px",
      "--pts-box": "278px",
      "--logo-size": "128px",
      "--mark-pad-x": "14px",
      "--mark-pad-y": "5px",
      "--stat-tint": "26",
      "--sparkle-opacity": "0",
      "--deco-opacity": "0",
      "--board-width": "100",
      "--font-display": '"Luckiest Guy", Impact, sans-serif',
      "--font-body": '"Oswald", "Arial Narrow", sans-serif',
      "--font-footer": '"Oswald", "Arial Narrow", sans-serif',
      "--highlight-rank": "0",
      "--move-up": "#1f9d4d",
      "--move-down": "#e23b36",
      "--move-flat": "#5c6570",
      "--title-shade": "#0b1622",
      "--title-shade-depth": "0px",
      "--outline-width": "12px",
      "--eyebrow-outline": "12px",
      "--rule-width": "0px",
      "--rule-height": "8px",
      "--hot-edge": "0px",
      "--arrow-size": "38px",
      "--kicker-tracking": "0.06em",
      "--plate-bg": "#ffffff",
      "--plate-ink": "#1a2748",
      "--bar-ink": "#ffffff",
      "--bar-ink-on-light": "#1a2748",
    },
  },
  {
    id: "power",
    name: "Power",
    blurb: "Left rank bars, red player slab",
    swatches: ["#1a1c20", "#c4122f", "#f4f4f6"],
    thumb: SAMPLE_HERO,
    hero: SAMPLE_HERO,
    ornaments: { a: "none", b: "none", c: "none", d: "none" },
    tokens: {
      "--poster-bg": "#1a1c20",
      "--poster-fg": "#ffffff",
      "--poster-muted": "#c8c8ce",
      "--poster-accent": "#c4122f",
      "--header-bar": "#f3f3f5",
      "--rank-fg": "#111111",
      "--rank-size": "30px",
      "--rank-width": "58px",
      "--trend-width": "40px",
      "--name-skew": "0",
      "--sparkle-opacity": "0",
      "--row-gap": "12px",
      "--row-height": "76px",
      "--row-radius": "0px",
      "--title-size": "54px",
      "--title-tracking": "0.03em",
      "--header-height": "132px",
      "--footer-height": "0px",
      "--name-size": "26px",
      "--stat-size": "18px",
      "--pts-box": "56px",
      "--pts-bg": "#111111",
      "--pts-fg": "#ffffff",
      "--poster-pad": "28px",
      "--deco-opacity": "0",
      "--font-display": '"Anton", Impact, sans-serif',
      "--font-body": '"Oswald", "Arial Narrow", sans-serif',
      "--font-footer": '"Oswald", "Arial Narrow", sans-serif',
      "--board-width": "54",
      "--hero-x": "240px",
      "--hero-y": "0px",
      "--hero-size": "1180px",
      "--hero-layer": "behind",
      "--hero-focus-x": "46",
      "--hero-focus-y": "30",
      "--cut-top": "0",
      "--cut-left": "52",
      "--cut-lean": "10",
      "--cut-pad": "16",
      "--highlight-rank": "0",
      "--move-up": "#22c55e",
      "--move-down": "#ef4444",
      "--move-flat": "#5a5a62",
      "--hot-edge": "0px",
      "--ghost-opacity": "0.1",
      "--pts-badge": "40px",
      "--kicker-tracking": "0.28em",
      "--kicker-size": "12px",
      "--photo-contrast": "1.08",
      "--photo-saturate": "1.1",
      "--plate-bg": "#ffffff",
      "--plate-ink": "#111111",
    },
  },
  {
    id: "split",
    name: "Split",
    blurb: "Diagonal photo cut, stepped ranks",
    swatches: ["#070708", "#f5c518", "#ffffff"],
    thumb: SAMPLE_HERO,
    hero: SAMPLE_HERO,
    ornaments: { a: "none", b: "none", c: "none", d: "none" },
    tokens: {
      "--poster-bg": "#070708",
      "--poster-fg": "#ffffff",
      "--poster-muted": "#a8a8b0",
      "--poster-accent": "#f5c518",
      "--header-bar": "#070708",
      "--rank-fg": "#ffffff",
      "--rank-size": "32px",
      "--rank-width": "62px",
      "--trend-width": "46px",
      "--name-skew": "0",
      "--sparkle-opacity": "0",
      "--row-gap": "3px",
      "--row-height": "74px",
      "--row-radius": "4px",
      "--row-stagger": "150px",
      "--split-cut": "36",
      "--split-gutter": "20px",
      "--split-edge": "8px",
      "--title-size": "78px",
      "--title-tracking": "0.02em",
      "--eyebrow-size": "30px",
      "--meta-size": "14px",
      "--header-height": "152px",
      "--footer-height": "52px",
      "--col-head-height": "24px",
      "--name-size": "24px",
      "--stat-size": "18px",
      "--pts-box": "76px",
      "--pts-bg": "#ffffff",
      "--pts-fg": "#050505",
      "--poster-pad": "28px",
      "--deco-opacity": "0",
      "--font-display": '"Anton", Impact, sans-serif',
      "--font-body": '"Oswald", "Arial Narrow", sans-serif',
      "--font-footer": '"Oswald", "Arial Narrow", sans-serif',
      "--board-width": "100",
      "--hero-x": "-220px",
      "--hero-y": "0px",
      "--hero-size": "1520px",
      "--hero-layer": "behind",
      "--hero-focus-x": "24",
      "--hero-focus-y": "16",
      "--rule-width": "88px",
      "--highlight-rank": "1",
      "--move-up": "#5ada8d",
      "--move-down": "#ff7c6c",
      "--move-flat": "#5a5a62",
      "--kicker-size": "14px",
      "--kicker-tracking": "0.32em",
      "--name-pad": "14px",
      "--logo-scale": "78",
      "--rule-height": "5px",
      "--footer-size": "13px",
      "--footer-tracking": "0.2em",
      "--photo-contrast": "1.06",
      "--photo-saturate": "1.08",
      "--plate-bg": "#ffffff",
      "--plate-ink": "#0a0a0a",
    },
  },
];

export function getTemplate(id: TemplateId): TemplateDef {
  return TEMPLATES.find((item) => item.id === id) ?? TEMPLATES[0];
}

export function tokensForTemplate(id: TemplateId): Record<string, string> {
  return { ...DEFAULT_TOKENS, ...getTemplate(id).tokens };
}
