import type { TokenDef } from "../engine/types";

/** Defaults Demi can also see in tokens.css. Inspector starts here. */
export const DEFAULT_TOKENS: Record<string, string> = {
  "--poster-bg": "#07080c",
  "--poster-fg": "#ffffff",
  "--poster-muted": "#d8d0c4",
  "--poster-accent": "#e4b53c",
  "--poster-pad": "48px",
  "--header-height": "150px",
  "--title-size": "92px",
  "--title-tracking": "0.02em",
  "--title-x": "0px",
  "--title-y": "0px",
  "--list-x": "0px",
  "--list-y": "0px",
  "--footer-size": "22px",
  "--footer-height": "72px",
  "--col-head-height": "38px",
  "--row-height": "92px",
  "--row-gap": "14px",
  "--name-size": "28px",
  "--stat-size": "22px",
  "--stat-col-width": "52px",
  "--pts-box": "64px",
  "--pts-bg": "#ffffff",
  "--pts-fg": "#e4b53c",
  "--header-bar": "#e4b53c",
  "--logo-size": "92px",
  "--rank-width": "56px",
  "--rank-size": "28px",
  "--rank-fg": "#e4b53c",
  "--name-skew": "-8",
  "--sparkle-opacity": "0.85",
  "--deco-opacity": "0.55",
  "--deco-a-x": "760px",
  "--deco-a-y": "-30px",
  "--deco-a-size": "300px",
  "--deco-a-rotate": "18",
  "--deco-b-x": "-70px",
  "--deco-b-y": "1080px",
  "--deco-b-size": "240px",
  "--deco-b-rotate": "-24",
  "--font-display": '"Permanent Marker", "Comic Sans MS", cursive',
  "--font-body": '"Oswald", "Arial Narrow", sans-serif',
  "--font-footer": '"Oswald", "Arial Narrow", sans-serif',
};

export const TOKEN_DEFS: TokenDef[] = [
  { id: "--poster-bg", label: "Poster background", group: "Canvas", kind: "color" },
  { id: "--poster-accent", label: "Gold / theme", group: "Canvas", kind: "color" },
  { id: "--header-bar", label: "Stats header bar", group: "Canvas", kind: "color" },
  { id: "--poster-fg", label: "Main text", group: "Canvas", kind: "color" },
  { id: "--poster-pad", label: "Outer padding", group: "Canvas", kind: "px", min: 24, max: 96, step: 2 },
  { id: "--sparkle-opacity", label: "Sparkle amount", group: "Canvas", kind: "number", min: 0, max: 1, step: 0.05 },
  { id: "--header-height", label: "Title height", group: "Header", kind: "px", min: 80, max: 220, step: 4 },
  { id: "--title-size", label: "Title size", group: "Header", kind: "px", min: 40, max: 140, step: 2 },
  { id: "--title-tracking", label: "Title tracking", group: "Header", kind: "em", min: -0.04, max: 0.12, step: 0.01 },
  { id: "--col-head-height", label: "Column header height", group: "Header", kind: "px", min: 24, max: 56, step: 1 },
  { id: "--footer-size", label: "Footer size", group: "Header", kind: "px", min: 12, max: 36, step: 1 },
  { id: "--footer-height", label: "Footer height", group: "Header", kind: "px", min: 40, max: 120, step: 2 },
  { id: "--title-x", label: "Title left / right", group: "Layout", kind: "px", min: -200, max: 200, step: 4 },
  { id: "--title-y", label: "Title up / down", group: "Layout", kind: "px", min: -120, max: 160, step: 4 },
  { id: "--list-x", label: "Table left / right", group: "Layout", kind: "px", min: -160, max: 160, step: 4 },
  { id: "--list-y", label: "Table up / down", group: "Layout", kind: "px", min: -160, max: 200, step: 4 },
  { id: "--row-height", label: "Row height", group: "Row", kind: "px", min: 56, max: 140, step: 2 },
  { id: "--row-gap", label: "Gap between rows", group: "Row", kind: "px", min: 0, max: 28, step: 1 },
  { id: "--name-skew", label: "Name slant", group: "Row", kind: "number", min: -16, max: 0, step: 1 },
  { id: "--stat-col-width", label: "Stat column width", group: "Row", kind: "px", min: 36, max: 80, step: 1 },
  { id: "--pts-box", label: "PTS / rating box", group: "Row", kind: "px", min: 40, max: 96, step: 1 },
  { id: "--pts-bg", label: "PTS box fill", group: "Row", kind: "color" },
  { id: "--pts-fg", label: "PTS number", group: "Row", kind: "color" },
  { id: "--rank-width", label: "Rank column", group: "Row", kind: "px", min: 36, max: 88, step: 2 },
  { id: "--rank-size", label: "Rank size", group: "Type", kind: "px", min: 16, max: 48, step: 1 },
  { id: "--rank-fg", label: "Rank color", group: "Type", kind: "color" },
  { id: "--name-size", label: "Team name size", group: "Type", kind: "px", min: 16, max: 48, step: 1 },
  { id: "--stat-size", label: "Stat number size", group: "Type", kind: "px", min: 12, max: 36, step: 1 },
  { id: "--font-display", label: "Title / name font", group: "Type", kind: "font" },
  { id: "--font-body", label: "Stats font", group: "Type", kind: "font" },
  { id: "--font-footer", label: "Footer font", group: "Type", kind: "font" },
  { id: "--logo-size", label: "Logo box", group: "Logo", kind: "px", min: 48, max: 140, step: 2 },
  { id: "--deco-opacity", label: "Sticker opacity", group: "Stickers", kind: "number", min: 0, max: 1, step: 0.05 },
  { id: "--deco-a-x", label: "Sticker 1 left", group: "Stickers", kind: "px", min: -200, max: 1000, step: 8 },
  { id: "--deco-a-y", label: "Sticker 1 top", group: "Stickers", kind: "px", min: -200, max: 1400, step: 8 },
  { id: "--deco-a-size", label: "Sticker 1 size", group: "Stickers", kind: "px", min: 80, max: 480, step: 8 },
  { id: "--deco-a-rotate", label: "Sticker 1 rotate", group: "Stickers", kind: "number", min: -180, max: 180, step: 2 },
  { id: "--deco-b-x", label: "Sticker 2 left", group: "Stickers", kind: "px", min: -200, max: 1000, step: 8 },
  { id: "--deco-b-y", label: "Sticker 2 top", group: "Stickers", kind: "px", min: -200, max: 1400, step: 8 },
  { id: "--deco-b-size", label: "Sticker 2 size", group: "Stickers", kind: "px", min: 80, max: 480, step: 8 },
  { id: "--deco-b-rotate", label: "Sticker 2 rotate", group: "Stickers", kind: "number", min: -180, max: 180, step: 2 },
];

export const FONT_OPTIONS = [
  '"Permanent Marker", "Comic Sans MS", cursive',
  '"Oswald", "Arial Narrow", sans-serif',
  '"Bebas Neue", Impact, sans-serif',
  '"Fraunces", Georgia, serif',
  '"IBM Plex Sans", sans-serif',
  "Georgia, serif",
  "system-ui, sans-serif",
];

export const TOKEN_GROUPS = ["Canvas", "Header", "Layout", "Row", "Type", "Logo", "Stickers"];
