import type { TokenDef } from "../engine/types";

/** Defaults Demi can also see in tokens.css. Inspector starts here. */
export const DEFAULT_TOKENS: Record<string, string> = {
  "--poster-bg": "#07080c",
  "--poster-fg": "#ffffff",
  "--poster-muted": "#d8d0c4",
  "--poster-accent": "#e4b53c",
  "--poster-pad": "48px",
  "--header-height": "150px",
  "--title-size": "92px",
  "--title-tracking": "0.02em",
  "--title-x": "0px",
  "--title-y": "0px",
  "--title-shade": "#000000",
  "--title-shade-depth": "2px",
  "--title-outline": "#ffffff",
  "--outline-width": "5px",
  "--list-x": "0px",
  "--list-y": "0px",
  "--footer-size": "22px",
  "--footer-height": "72px",
  "--footer-tracking": "0.16em",
  "--kicker-size": "13px",
  "--kicker-tracking": "0.34em",
  "--col-head-height": "38px",
  "--col-head-size": "15px",
  "--col-head-fg": "#ffffff",
  "--row-height": "92px",
  "--row-gap": "14px",
  "--row-radius": "0px",
  "--row-edge": "0px",
  "--name-size": "28px",
  "--name-skew": "-8",
  "--name-pad": "16px",
  "--stat-size": "22px",
  "--stat-col-width": "52px",
  "--stat-fg": "#ffffff",
  "--stat-tint": "16",
  "--pts-box": "64px",
  "--pts-bg": "#ffffff",
  "--pts-fg": "#e4b53c",
  "--pts-badge": "48px",
  "--header-bar": "#e4b53c",
  "--logo-size": "92px",
  "--logo-scale": "100",
  "--rank-width": "56px",
  "--rank-size": "28px",
  "--rank-fg": "#e4b53c",
  "--plate-bg": "#ffffff",
  "--plate-ink": "#14161c",
  "--move-up": "#7dffb3",
  "--move-down": "#ff8d7a",
  "--move-flat": "#98a0a8",
  "--arrow-size": "26px",
  "--hot-edge": "4px",
  "--rule-height": "7px",
  "--ghost-size": "128px",
  "--ghost-opacity": "0.16",
  "--sparkle-color": "#f7e08a",
  "--sparkle-opacity": "0.85",
  "--deco-opacity": "0.55",
  "--deco-a-x": "760px",
  "--deco-a-y": "-30px",
  "--deco-a-size": "300px",
  "--deco-a-rotate": "18",
  "--deco-b-x": "-70px",
  "--deco-b-y": "1080px",
  "--deco-b-size": "240px",
  "--deco-b-rotate": "-24",
  "--deco-c-x": "-48px",
  "--deco-c-y": "-24px",
  "--deco-c-size": "180px",
  "--deco-c-rotate": "-12",
  "--deco-d-x": "820px",
  "--deco-d-y": "1180px",
  "--deco-d-size": "160px",
  "--deco-d-rotate": "14",
  "--bg-dim": "0.58",
  "--watermark-opacity": "0.14",
  "--watermark-size": "72",
  "--header-mark-size": "88px",
  "--footer-badge-size": "52px",
  "--font-display": '"Permanent Marker", "Comic Sans MS", cursive',
  "--font-body": '"Oswald", "Arial Narrow", sans-serif',
  "--font-footer": '"Oswald", "Arial Narrow", sans-serif',
  "--board-width": "100",
  "--hero-x": "420px",
  "--hero-y": "120px",
  "--hero-size": "640px",
  "--hero-h": "0px",
  "--hero-layer": "behind",
  "--hero-focus-x": "50",
  "--hero-focus-y": "42",
  "--cut-top": "14",
  "--cut-left": "35",
  "--cut-lean": "8",
  "--cut-pad": "7",
  "--rule-width": "88px",
  "--photo-contrast": "1",
  "--photo-saturate": "1",
  "--highlight-rank": "1",
  "--row-stagger": "0px",
  "--seg-gap": "0px",
  "--split-cut": "34",
  "--split-gutter": "20px",
  "--split-edge": "6px",
  "--trend-width": "76px",
  "--meta-size": "15px",
  "--eyebrow-size": "34px",
  "--bar-ink": "#f0e4c4",
  "--bar-ink-on-light": "#1a2748",
};

/**
 * Every control the user sees. A token that changes the poster belongs here — templates
 * only preset these values, they never own a look the user cannot reach.
 */
export const TOKEN_DEFS: TokenDef[] = [
  // Color
  { id: "--poster-bg", label: "Background", group: "Color", kind: "color" },
  { id: "--poster-accent", label: "Theme", group: "Color", kind: "color" },
  { id: "--poster-fg", label: "Text", group: "Color", kind: "color" },
  { id: "--poster-muted", label: "Muted text", group: "Color", kind: "color" },
  { id: "--rank-fg", label: "Rank number", group: "Color", kind: "color" },
  { id: "--pts-bg", label: "Rating box", group: "Color", kind: "color" },
  { id: "--pts-fg", label: "Rating text", group: "Color", kind: "color" },
  { id: "--stat-fg", label: "Stat text", group: "Color", kind: "color" },
  { id: "--header-bar", label: "Header bar", group: "Color", kind: "color" },
  { id: "--col-head-fg", label: "Column labels", group: "Color", kind: "color" },
  { id: "--plate-bg", label: "Plate fill", group: "Color", kind: "color" },
  { id: "--plate-ink", label: "Plate text", group: "Color", kind: "color" },
  { id: "--move-up", label: "Moved up", group: "Color", kind: "color" },
  { id: "--move-down", label: "Moved down", group: "Color", kind: "color" },
  { id: "--move-flat", label: "No change", group: "Color", kind: "color" },
  { id: "--title-outline", label: "Title outline", group: "Color", kind: "color" },
  { id: "--title-shade", label: "Title shadow", group: "Color", kind: "color" },
  { id: "--sparkle-color", label: "Sparkle", group: "Color", kind: "color" },
  { id: "--stat-tint", label: "Stat panel tint", group: "Color", kind: "number", min: 0, max: 60, step: 1 },
  { id: "--bar-ink", label: "Bar text (dark rows)", group: "Color", kind: "color" },
  { id: "--bar-ink-on-light", label: "Bar text (light rows)", group: "Color", kind: "color" },

  // Type
  { id: "--title-size", label: "Title size", group: "Type", kind: "px", min: 40, max: 160, step: 2 },
  { id: "--title-tracking", label: "Title tracking", group: "Type", kind: "em", min: -0.04, max: 0.3, step: 0.01 },
  { id: "--outline-width", label: "Title outline width", group: "Type", kind: "px", min: 0, max: 14, step: 1 },
  { id: "--title-shade-depth", label: "Title shadow depth", group: "Type", kind: "px", min: 0, max: 20, step: 1 },
  { id: "--eyebrow-size", label: "Sport line size", group: "Type", kind: "px", min: 14, max: 72, step: 1 },
  { id: "--kicker-size", label: "Kicker size", group: "Type", kind: "px", min: 8, max: 40, step: 1 },
  { id: "--kicker-tracking", label: "Kicker tracking", group: "Type", kind: "em", min: 0, max: 0.6, step: 0.02 },
  { id: "--meta-size", label: "Top note size", group: "Type", kind: "px", min: 9, max: 30, step: 1 },
  { id: "--name-size", label: "Team name size", group: "Type", kind: "px", min: 12, max: 52, step: 1 },
  { id: "--rank-size", label: "Rank size", group: "Type", kind: "px", min: 10, max: 72, step: 1 },
  { id: "--stat-size", label: "Stat size", group: "Type", kind: "px", min: 9, max: 40, step: 1 },
  { id: "--col-head-size", label: "Column label size", group: "Type", kind: "px", min: 8, max: 34, step: 1 },
  { id: "--footer-size", label: "Footer size", group: "Type", kind: "px", min: 8, max: 40, step: 1 },
  { id: "--footer-tracking", label: "Footer tracking", group: "Type", kind: "em", min: 0, max: 0.5, step: 0.02 },
  { id: "--font-display", label: "Title / names", group: "Type", kind: "font" },
  { id: "--font-body", label: "Stats", group: "Type", kind: "font" },
  { id: "--font-footer", label: "Footer", group: "Type", kind: "font" },

  // Rows
  { id: "--row-height", label: "Row height", group: "Rows", kind: "px", min: 40, max: 140, step: 2 },
  { id: "--row-gap", label: "Row gap", group: "Rows", kind: "px", min: 0, max: 40, step: 1 },
  { id: "--row-radius", label: "Row corners", group: "Rows", kind: "px", min: 0, max: 40, step: 1 },
  { id: "--row-edge", label: "Team colour edge", group: "Rows", kind: "px", min: 0, max: 24, step: 1 },
  { id: "--seg-gap", label: "Segment gap", group: "Rows", kind: "px", min: 0, max: 32, step: 1 },
  { id: "--name-pad", label: "Name padding", group: "Rows", kind: "px", min: 0, max: 48, step: 1 },
  { id: "--name-skew", label: "Name slant", group: "Rows", kind: "number", min: -20, max: 20, step: 1 },
  { id: "--logo-scale", label: "Crest size %", group: "Rows", kind: "number", min: 30, max: 100, step: 1 },
  { id: "--rank-width", label: "Rank column", group: "Rows", kind: "px", min: 26, max: 160, step: 2 },
  { id: "--trend-width", label: "Trend column", group: "Rows", kind: "px", min: 0, max: 160, step: 2 },
  { id: "--stat-col-width", label: "Stat column", group: "Rows", kind: "px", min: 24, max: 140, step: 2 },
  { id: "--pts-box", label: "Rating column", group: "Rows", kind: "px", min: 40, max: 240, step: 2 },
  { id: "--pts-badge", label: "Rating badge", group: "Rows", kind: "px", min: 24, max: 120, step: 2 },
  { id: "--arrow-size", label: "Arrow size", group: "Rows", kind: "px", min: 8, max: 48, step: 1 },
  { id: "--hot-edge", label: "Highlight edge", group: "Rows", kind: "px", min: 0, max: 12, step: 1 },
  { id: "--rule-width", label: "Title rule length", group: "Rows", kind: "px", min: 0, max: 280, step: 2 },
  { id: "--ghost-size", label: "Ghost rank size", group: "Rows", kind: "px", min: 40, max: 260, step: 4 },
  { id: "--ghost-opacity", label: "Ghost opacity", group: "Rows", kind: "number", min: 0, max: 1, step: 0.01 },
  { id: "--row-stagger", label: "Diagonal travel", group: "Rows", kind: "px", min: 0, max: 420, step: 5 },
  { id: "--split-cut", label: "Diagonal start %", group: "Rows", kind: "number", min: 0, max: 70, step: 1 },
  { id: "--split-gutter", label: "Diagonal gutter", group: "Rows", kind: "px", min: 0, max: 90, step: 2 },
  { id: "--split-edge", label: "Diagonal edge", group: "Rows", kind: "px", min: 0, max: 24, step: 1 },

  // Photo
  { id: "--hero-x", label: "Photo left / right", group: "Photo", kind: "px", min: -400, max: 900, step: 8 },
  { id: "--hero-y", label: "Photo up / down", group: "Photo", kind: "px", min: -400, max: 1100, step: 8 },
  { id: "--hero-size", label: "Photo width", group: "Photo", kind: "px", min: 220, max: 2200, step: 8 },
  { id: "--hero-h", label: "Photo height", group: "Photo", kind: "px", min: 0, max: 2200, step: 8 },
  { id: "--hero-focus-x", label: "Photo crop left / right", group: "Photo", kind: "number", min: 0, max: 100, step: 1 },
  { id: "--hero-focus-y", label: "Photo crop up / down", group: "Photo", kind: "number", min: 0, max: 100, step: 1 },
  { id: "--cut-top", label: "Cutout from top %", group: "Photo", kind: "number", min: 0, max: 60, step: 1 },
  { id: "--cut-left", label: "Cutout from left %", group: "Photo", kind: "number", min: 0, max: 80, step: 1 },
  { id: "--cut-lean", label: "Cutout lean", group: "Photo", kind: "number", min: 0, max: 40, step: 1 },
  { id: "--cut-pad", label: "Cutout photo inset", group: "Photo", kind: "number", min: 0, max: 30, step: 1 },
  { id: "--photo-contrast", label: "Photo contrast", group: "Photo", kind: "number", min: 0.5, max: 2, step: 0.02 },
  { id: "--photo-saturate", label: "Photo saturation", group: "Photo", kind: "number", min: 0, max: 2, step: 0.02 },
  { id: "--bg-dim", label: "Background dim", group: "Photo", kind: "number", min: 0, max: 1, step: 0.01 },
  { id: "--watermark-size", label: "Watermark size %", group: "Photo", kind: "number", min: 10, max: 140, step: 2 },
  { id: "--watermark-opacity", label: "Watermark opacity", group: "Photo", kind: "number", min: 0, max: 1, step: 0.01 },
  { id: "--header-mark-size", label: "Header logo size", group: "Photo", kind: "px", min: 0, max: 260, step: 4 },
  { id: "--footer-badge-size", label: "Footer badge size", group: "Photo", kind: "px", min: 0, max: 200, step: 4 },

  // Stickers
  { id: "--deco-opacity", label: "Sticker opacity", group: "Stickers", kind: "number", min: 0, max: 1, step: 0.01 },
  { id: "--sparkle-opacity", label: "Sparkle opacity", group: "Stickers", kind: "number", min: 0, max: 1, step: 0.01 },
  { id: "--deco-a-x", label: "Sticker 1 left / right", group: "Stickers", kind: "px", min: -400, max: 1200, step: 2 },
  { id: "--deco-a-y", label: "Sticker 1 up / down", group: "Stickers", kind: "px", min: -400, max: 1500, step: 2 },
  { id: "--deco-a-size", label: "Sticker 1 size", group: "Stickers", kind: "px", min: 40, max: 700, step: 2 },
  { id: "--deco-a-rotate", label: "Sticker 1 rotate", group: "Stickers", kind: "number", min: -180, max: 180, step: 2 },
  { id: "--deco-b-x", label: "Sticker 2 left / right", group: "Stickers", kind: "px", min: -400, max: 1200, step: 2 },
  { id: "--deco-b-y", label: "Sticker 2 up / down", group: "Stickers", kind: "px", min: -400, max: 1500, step: 2 },
  { id: "--deco-b-size", label: "Sticker 2 size", group: "Stickers", kind: "px", min: 40, max: 700, step: 2 },
  { id: "--deco-b-rotate", label: "Sticker 2 rotate", group: "Stickers", kind: "number", min: -180, max: 180, step: 2 },
  { id: "--deco-c-x", label: "Sticker 3 left / right", group: "Stickers", kind: "px", min: -400, max: 1200, step: 2 },
  { id: "--deco-c-y", label: "Sticker 3 up / down", group: "Stickers", kind: "px", min: -400, max: 1500, step: 2 },
  { id: "--deco-c-size", label: "Sticker 3 size", group: "Stickers", kind: "px", min: 40, max: 700, step: 2 },
  { id: "--deco-c-rotate", label: "Sticker 3 rotate", group: "Stickers", kind: "number", min: -180, max: 180, step: 2 },
  { id: "--deco-d-x", label: "Sticker 4 left / right", group: "Stickers", kind: "px", min: -400, max: 1200, step: 2 },
  { id: "--deco-d-y", label: "Sticker 4 up / down", group: "Stickers", kind: "px", min: -400, max: 1500, step: 2 },
  { id: "--deco-d-size", label: "Sticker 4 size", group: "Stickers", kind: "px", min: 40, max: 700, step: 2 },
  { id: "--deco-d-rotate", label: "Sticker 4 rotate", group: "Stickers", kind: "number", min: -180, max: 180, step: 2 },

  // Place
  { id: "--poster-pad", label: "Poster padding", group: "Place", kind: "px", min: 0, max: 96, step: 2 },
  { id: "--list-x", label: "Board left / right", group: "Place", kind: "px", min: -240, max: 240, step: 4 },
  { id: "--list-y", label: "Board up / down", group: "Place", kind: "px", min: -200, max: 200, step: 4 },
  { id: "--board-width", label: "Board width %", group: "Place", kind: "number", min: 42, max: 100, step: 1 },
  { id: "--header-height", label: "Header height", group: "Place", kind: "px", min: 60, max: 420, step: 4 },
  { id: "--title-x", label: "Title left / right", group: "Place", kind: "px", min: -240, max: 240, step: 4 },
  { id: "--title-y", label: "Title up / down", group: "Place", kind: "px", min: -200, max: 200, step: 4 },
  { id: "--col-head-height", label: "Column head height", group: "Place", kind: "px", min: 0, max: 90, step: 2 },
  { id: "--footer-height", label: "Footer height", group: "Place", kind: "px", min: 0, max: 200, step: 4 },
  { id: "--rule-height", label: "Divider rule", group: "Place", kind: "px", min: 0, max: 24, step: 1 },
  { id: "--highlight-rank", label: "Highlight row", group: "Place", kind: "number", min: 0, max: 25, step: 1 },
];

/** First-run Look panel. Everything else sits behind More look. */
export const SIMPLE_LOOK_IDS = ["--poster-bg", "--poster-accent", "--title-size"] as const;

/** Extra Look controls shown after More look. Simple colors/title stay at the top. */
export const ESSENTIAL_TOKEN_IDS = new Set([
  "--poster-bg",
  "--poster-accent",
  "--poster-fg",
  "--title-size",
  "--name-size",
  "--font-display",
  "--row-height",
  "--row-gap",
  "--hero-x",
  "--hero-y",
  "--hero-size",
  "--poster-pad",
  "--board-width",
]);

/** Extra essentials that only matter on specific layouts. */
export const TEMPLATE_TOKEN_IDS: Record<string, string[]> = {
  split: ["--row-stagger", "--split-cut", "--split-gutter", "--split-edge", "--hero-focus-x", "--hero-focus-y"],
  power: ["--header-bar", "--cut-top", "--cut-left", "--cut-lean", "--hero-focus-x", "--hero-focus-y"],
  board: ["--title-outline", "--stat-tint", "--bar-ink", "--bar-ink-on-light"],
  movers: ["--seg-gap", "--row-radius"],
};

export const FONT_OPTIONS = [
  '"Luckiest Guy", Impact, sans-serif',
  '"Permanent Marker", "Comic Sans MS", cursive',
  '"Oswald", "Arial Narrow", sans-serif',
  '"Bebas Neue", Impact, sans-serif',
  '"Anton", Impact, sans-serif',
  '"Playfair Display", Georgia, serif',
  '"Fraunces", Georgia, serif',
  '"IBM Plex Sans", sans-serif',
  "Georgia, serif",
  "system-ui, sans-serif",
];

export const TOKEN_GROUPS = ["Color", "Type", "Rows", "Photo", "Stickers", "Place"];
